/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;
import dao.DadosDAO;
import dao.EconomiaDao;
import Classes.Economia;
import Classes.Dados;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author leo_z
 */
public class TelaDados extends javax.swing.JFrame {
    
    EconomiaDao eco = new EconomiaDao();
    DadosDAO dados = new DadosDAO();
    Economia ecos= new Economia();
    public Integer comprado;
    
    public TelaDados() {
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon.png")).getImage());
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("DataWatchers");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        painelismael = new javax.swing.JPanel();
        txtnome1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botaoismael = new javax.swing.JButton();
        txtnome6 = new javax.swing.JLabel();
        txtnome11 = new javax.swing.JLabel();
        painelleo = new javax.swing.JPanel();
        txtnome0 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botaoleo = new javax.swing.JButton();
        txtnome3 = new javax.swing.JLabel();
        txtnome10 = new javax.swing.JLabel();
        painelMarlon = new javax.swing.JPanel();
        txtnome2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botaomarlon = new javax.swing.JButton();
        txtnome7 = new javax.swing.JLabel();
        txtnome12 = new javax.swing.JLabel();
        painelfelipe = new javax.swing.JPanel();
        txtnome4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botaofelipe = new javax.swing.JButton();
        txtnome8 = new javax.swing.JLabel();
        txtnome13 = new javax.swing.JLabel();
        paineljudas = new javax.swing.JPanel();
        txtnome5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botaogabriel = new javax.swing.JButton();
        txtnome9 = new javax.swing.JLabel();
        txtnome14 = new javax.swing.JLabel();
        botaovaltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelismael.setBackground(new java.awt.Color(102, 102, 102));

        txtnome1.setBackground(new java.awt.Color(0, 255, 0));
        txtnome1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome1.setForeground(new java.awt.Color(51, 255, 0));
        txtnome1.setText("Ismael Lucas");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 51));
        jLabel7.setText("Preço:1000");

        botaoismael.setBackground(new java.awt.Color(102, 102, 102));
        botaoismael.setText("Buy");
        botaoismael.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoismaelActionPerformed(evt);
            }
        });

        txtnome6.setBackground(new java.awt.Color(0, 255, 0));
        txtnome6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome6.setForeground(new java.awt.Color(51, 255, 0));
        txtnome6.setText("Ultimo Site acessado: www.Pratafina.com");

        txtnome11.setBackground(new java.awt.Color(0, 255, 0));
        txtnome11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome11.setForeground(new java.awt.Color(51, 255, 0));
        txtnome11.setText("A procura de uma Banda");

        javax.swing.GroupLayout painelismaelLayout = new javax.swing.GroupLayout(painelismael);
        painelismael.setLayout(painelismaelLayout);
        painelismaelLayout.setHorizontalGroup(
            painelismaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelismaelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelismaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelismaelLayout.createSequentialGroup()
                        .addComponent(txtnome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelismaelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtnome6)
                        .addGap(18, 18, 18)
                        .addComponent(botaoismael))
                    .addGroup(painelismaelLayout.createSequentialGroup()
                        .addComponent(txtnome11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelismaelLayout.setVerticalGroup(
            painelismaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelismaelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelismaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(txtnome11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelismaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoismael)
                    .addComponent(txtnome6))
                .addContainerGap())
        );

        jPanel3.add(painelismael, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 340, -1));

        painelleo.setBackground(new java.awt.Color(102, 102, 102));

        txtnome0.setBackground(new java.awt.Color(0, 255, 0));
        txtnome0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome0.setForeground(new java.awt.Color(51, 255, 0));
        txtnome0.setText("Leonardo Pimentel");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 51));
        jLabel6.setText("Preço:300");

        botaoleo.setBackground(new java.awt.Color(102, 102, 102));
        botaoleo.setText("Buy");
        botaoleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoleoActionPerformed(evt);
            }
        });

        txtnome3.setBackground(new java.awt.Color(0, 255, 0));
        txtnome3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome3.setForeground(new java.awt.Color(51, 255, 0));
        txtnome3.setText("Ultimo Site acessado: www.facebook.com");

        txtnome10.setBackground(new java.awt.Color(0, 255, 0));
        txtnome10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome10.setForeground(new java.awt.Color(51, 255, 0));
        txtnome10.setText("Procura muito sombre Pc Gamer");

        javax.swing.GroupLayout painelleoLayout = new javax.swing.GroupLayout(painelleo);
        painelleo.setLayout(painelleoLayout);
        painelleoLayout.setHorizontalGroup(
            painelleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelleoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelleoLayout.createSequentialGroup()
                        .addComponent(txtnome0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelleoLayout.createSequentialGroup()
                        .addComponent(txtnome3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoleo))
                    .addGroup(painelleoLayout.createSequentialGroup()
                        .addComponent(txtnome10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelleoLayout.setVerticalGroup(
            painelleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelleoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome0)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnome10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoleo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnome3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(21, 21, 21))
        );

        jPanel3.add(painelleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        painelMarlon.setBackground(new java.awt.Color(102, 102, 102));

        txtnome2.setBackground(new java.awt.Color(0, 255, 0));
        txtnome2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome2.setForeground(new java.awt.Color(51, 255, 0));
        txtnome2.setText("Marlon Friesen");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 51));
        jLabel8.setText("Preço:1300");

        botaomarlon.setBackground(new java.awt.Color(102, 102, 102));
        botaomarlon.setText("Buy");
        botaomarlon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaomarlonActionPerformed(evt);
            }
        });

        txtnome7.setBackground(new java.awt.Color(0, 255, 0));
        txtnome7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome7.setForeground(new java.awt.Color(51, 255, 0));
        txtnome7.setText("Ultimo Site acessado: www.Nasa.com");

        txtnome12.setBackground(new java.awt.Color(0, 255, 0));
        txtnome12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome12.setForeground(new java.awt.Color(51, 255, 0));
        txtnome12.setText("Trazendo Pneus Importados");

        javax.swing.GroupLayout painelMarlonLayout = new javax.swing.GroupLayout(painelMarlon);
        painelMarlon.setLayout(painelMarlonLayout);
        painelMarlonLayout.setHorizontalGroup(
            painelMarlonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMarlonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMarlonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMarlonLayout.createSequentialGroup()
                        .addComponent(txtnome2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMarlonLayout.createSequentialGroup()
                        .addComponent(txtnome7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaomarlon))
                    .addGroup(painelMarlonLayout.createSequentialGroup()
                        .addComponent(txtnome12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelMarlonLayout.setVerticalGroup(
            painelMarlonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMarlonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMarlonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnome12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelMarlonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaomarlon)
                    .addComponent(txtnome7))
                .addContainerGap())
        );

        jPanel3.add(painelMarlon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 340, -1));

        painelfelipe.setBackground(new java.awt.Color(102, 102, 102));

        txtnome4.setBackground(new java.awt.Color(0, 255, 0));
        txtnome4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome4.setForeground(new java.awt.Color(51, 255, 0));
        txtnome4.setText("Felipe");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 51));
        jLabel9.setText("Preço:2000");

        botaofelipe.setBackground(new java.awt.Color(102, 102, 102));
        botaofelipe.setText("Buy");
        botaofelipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaofelipeActionPerformed(evt);
            }
        });

        txtnome8.setBackground(new java.awt.Color(0, 255, 0));
        txtnome8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome8.setForeground(new java.awt.Color(51, 255, 0));
        txtnome8.setText("Ultimo Site acessado: www.Udemy.com");

        txtnome13.setBackground(new java.awt.Color(0, 255, 0));
        txtnome13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome13.setForeground(new java.awt.Color(51, 255, 0));
        txtnome13.setText("Fazendo Aplicaçoes para Nasa");

        javax.swing.GroupLayout painelfelipeLayout = new javax.swing.GroupLayout(painelfelipe);
        painelfelipe.setLayout(painelfelipeLayout);
        painelfelipeLayout.setHorizontalGroup(
            painelfelipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelfelipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelfelipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelfelipeLayout.createSequentialGroup()
                        .addComponent(txtnome4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelfelipeLayout.createSequentialGroup()
                        .addComponent(txtnome8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaofelipe))
                    .addGroup(painelfelipeLayout.createSequentialGroup()
                        .addComponent(txtnome13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelfelipeLayout.setVerticalGroup(
            painelfelipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelfelipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelfelipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(txtnome13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelfelipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaofelipe)
                    .addComponent(txtnome8))
                .addContainerGap())
        );

        jPanel3.add(painelfelipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 340, -1));

        paineljudas.setBackground(new java.awt.Color(102, 102, 102));

        txtnome5.setBackground(new java.awt.Color(0, 255, 0));
        txtnome5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome5.setForeground(new java.awt.Color(51, 255, 0));
        txtnome5.setText("Gabriel Judas");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 51));
        jLabel10.setText("Preço:2400");

        botaogabriel.setBackground(new java.awt.Color(102, 102, 102));
        botaogabriel.setText("Buy");
        botaogabriel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaogabrielActionPerformed(evt);
            }
        });

        txtnome9.setBackground(new java.awt.Color(0, 255, 0));
        txtnome9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome9.setForeground(new java.awt.Color(51, 255, 0));
        txtnome9.setText("Ultimo Site acessado: www.Google.com");

        txtnome14.setBackground(new java.awt.Color(0, 255, 0));
        txtnome14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome14.setForeground(new java.awt.Color(51, 255, 0));
        txtnome14.setText("Traindo Amigos em Jogos online");

        javax.swing.GroupLayout paineljudasLayout = new javax.swing.GroupLayout(paineljudas);
        paineljudas.setLayout(paineljudasLayout);
        paineljudasLayout.setHorizontalGroup(
            paineljudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paineljudasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paineljudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paineljudasLayout.createSequentialGroup()
                        .addComponent(txtnome5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paineljudasLayout.createSequentialGroup()
                        .addComponent(txtnome9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaogabriel))
                    .addGroup(paineljudasLayout.createSequentialGroup()
                        .addComponent(txtnome14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paineljudasLayout.setVerticalGroup(
            paineljudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paineljudasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paineljudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnome14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(paineljudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaogabriel)
                    .addComponent(txtnome9))
                .addContainerGap())
        );

        jPanel3.add(paineljudas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 340, -1));

        botaovaltar.setText("Voltar");
        botaovaltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaovaltarActionPerformed(evt);
            }
        });
        jPanel3.add(botaovaltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoleoActionPerformed
        // TODO add your handling code here:
        if(eco.PegarMoedasBanco()<300){
            JOptionPane.showMessageDialog(null,"BitCoin insuficiente, junte 300 pra comprar");
        }else{
            TelaEnigma enig = new TelaEnigma();
            enig.setVisible(true);        
            enig.setResizable(false);
            enig.receberid(1,"leonardo",300);
            painelleo.setVisible(false);
            dados.updatecompletos(1);
           
            
        }
    }//GEN-LAST:event_botaoleoActionPerformed

    private void botaovaltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaovaltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botaovaltarActionPerformed

    private void botaoismaelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoismaelActionPerformed
        // TODO add your handling code here:
        if(eco.PegarMoedasBanco()<1000){
            JOptionPane.showMessageDialog(null,"BitCoin insuficiente, junte 1000 pra comprar");
        }else{
            TelaEnigma enig = new TelaEnigma();
            enig.setVisible(true);        
            enig.setResizable(false);
            enig.receberid(2,"ismael",1000);
            painelismael.setVisible(false);
            dados.updatecompletos(2);
            
            
        }
    }//GEN-LAST:event_botaoismaelActionPerformed

    private void botaomarlonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaomarlonActionPerformed
        // TODO add your handling code here:
        if(eco.PegarMoedasBanco()<1300){
            JOptionPane.showMessageDialog(null,"BitCoin insuficiente, junte 1300 pra comprar");
        }else{
            TelaEnigma enig = new TelaEnigma();
            enig.setVisible(true);        
            enig.setResizable(false);
            enig.receberid(3,"Marlon",1300);
            painelMarlon.setVisible(false);
            dados.updatecompletos(3);
            
            
        }
    }//GEN-LAST:event_botaomarlonActionPerformed

    private void botaofelipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaofelipeActionPerformed
        // TODO add your handling code here:
        if(eco.PegarMoedasBanco()<2000){
            JOptionPane.showMessageDialog(null,"BitCoin insuficiente, junte 2000 pra comprar");
        }else{
            TelaEnigma enig = new TelaEnigma();
            enig.setVisible(true);        
            enig.setResizable(false);
            enig.receberid(4,"Felipe",2000);
            painelfelipe.setVisible(false);
            dados.updatecompletos(4);
            
            
        }
    }//GEN-LAST:event_botaofelipeActionPerformed

    private void botaogabrielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaogabrielActionPerformed
        // TODO add your handling code here:
        if(eco.PegarMoedasBanco()<2400){
            JOptionPane.showMessageDialog(null,"BitCoin insuficiente, junte 2400 pra comprar");
        }else{
            TelaEnigma enig = new TelaEnigma();
            enig.setVisible(true);        
            enig.setResizable(false);
            enig.receberid(5,"Gabriel",2400);
            paineljudas.setVisible(false);
            dados.updatecompletos(5);
            this.dispose();
        }
    }//GEN-LAST:event_botaogabrielActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaofelipe;
    private javax.swing.JButton botaogabriel;
    private javax.swing.JButton botaoismael;
    private javax.swing.JButton botaoleo;
    private javax.swing.JButton botaomarlon;
    private javax.swing.JButton botaovaltar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel painelMarlon;
    private javax.swing.JPanel painelfelipe;
    private javax.swing.JPanel painelismael;
    private javax.swing.JPanel paineljudas;
    private javax.swing.JPanel painelleo;
    private javax.swing.JLabel txtnome0;
    private javax.swing.JLabel txtnome1;
    private javax.swing.JLabel txtnome10;
    private javax.swing.JLabel txtnome11;
    private javax.swing.JLabel txtnome12;
    private javax.swing.JLabel txtnome13;
    private javax.swing.JLabel txtnome14;
    private javax.swing.JLabel txtnome2;
    private javax.swing.JLabel txtnome3;
    private javax.swing.JLabel txtnome4;
    private javax.swing.JLabel txtnome5;
    private javax.swing.JLabel txtnome6;
    private javax.swing.JLabel txtnome7;
    private javax.swing.JLabel txtnome8;
    private javax.swing.JLabel txtnome9;
    // End of variables declaration//GEN-END:variables

    
    
}
